project:
  type: website
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
    - "!posts/titan-llama/**"
    - "!posts/titan-llama-archive/**"
    - "!posts/titan-llama-part-two/**"

website:
  title: "Rabbitholes"
  description: "Sarah Pan spends too much time doing random things"
  navbar:
    background: light
    search: false
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sarahpannn
      - icon: twitter
        href: https://x.com/spantacular

format:
  html:
    theme: 
      light: [cosmo, styles.css]
    html-math-method: katex
    toc: true
    code-copy: true
    anchor-sections: true

page-layout: full
